<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="recursos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="recurso" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="recurso_id" type="xs:integer"/>
              <xs:element name="recurso_nombre" type="xs:string"/>
              <xs:element name="recurso_precio" type="xs:decimal"/>
              <xs:element name="recurso_estado">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="En reserva"/>
                    <xs:enumeration value="En reparación"/>
                    <xs:enumeration value="Disponible"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="recurso_ubicacion" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

